### ISSUE TITLE
Imena na x-osi grafa

### ISSUE THREAD

**Issue by vesnazupanc** [vesnazupanc/APPR-2015-16#2]
Problem imam pri imenih na x-osi obeh grafov, saj so predolga in se prekrivajo. Ali je kakšna možnost, da se imena izpišejo navzdol?

**Comment by jaanos** [comment]
Grafu lahko prišteješ npr. `theme(axis.text.x = element_text(angle = 90, vjust = 0.5))`, da se imena izpišejo navpično.
