### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by jaanos** [vesnazupanc/APPR-2015-16#3]
Poročila pri meni ne prevede, ker je pri uvozu navedeno napačno kodiranje znakov in tako se podatki ne poračunajo pravilno. Pri uvozu razpredelnice `umrli.starost` tako uporabi kodiranje `"UTF-8"`.

**Comment by vesnazupanc** [comment]
Sem probala, pa mi sploh ne deluje.. Doma mi je vse v redu prevedlo, sedaj pa ko sem na faksu, ne prevede več.. 
Problem je da mi kode UTF-8 sploh ne vzame, oziroma je ne znam uporabiti, šele potem ko vse spremenim v character lahko uporabim.

Če kodo naprimer uporabim v `umrli.starost` mi vrne prazno tabelo.

**Comment by jaanos** [comment]
`"UTF-8"` nastavi pri funkciji `read.csv2` namesto `"cp1250"`.

**Comment by vesnazupanc** [comment]
Ali lahko mogoče preverite, če sedaj dela? Ker pri meni normalno prevede poročilo.

**Comment by jaanos** [comment]
Trenutno ne deluje - deluje pa, če upoštevam svoj prejšnji komentar.

**Comment by vesnazupanc** [comment]
Če uporabim "UTF-8" mi  vrne prazno tabelo.

**Comment by vesnazupanc** [comment]
Zdaj mi dela, hvala.
