### ISSUE TITLE
Zamenjava nizov v tabeli

### ISSUE THREAD

**Issue by vesnazupanc** [vesnazupanc/APPR-2015-16#4]
Zanima me, kako bi lahko v tabeli umrli.vzrok spremenila poimenovanje bolezni v stolpcu Vzrok, npr.:
vse "Bolezni dihal (J00-J99)" bi zamenjala z "Bolezni dihal" in enako za ostale bolezni?

**Comment by jaanos** [comment]
Najlažje bo, če pobereš vse znake do prvega presledka pred oklepajem. Obenem lahko stolpec še pretvoriš v faktor, da bo lažje združevanje in prikazovanje:

``` R
umrli.vzrok$Vzrok <- umrli.vzrok$Vzrok %>%
  strapplyc("^([^(]*) \\(") %>% unlist() %>% factor()
```

**Comment by vesnazupanc** [comment]
če to uporabim mi vrne:
[[1]]
character(0)
oz. mi posledično noče spremeniti..

**Comment by vesnazupanc** [comment]
Error in `$<-.data.frame`(`*tmp*`, "Vzrok", value = integer(0)) : 
  replacement has 0 rows, data has 600

to je napaka, ki mi jo javi.

**Comment by jaanos** [comment]
Najbrž si ukaz pognala dvakrat. Poskusi ga kar vključiti v `uvoz.r` in še enkrat zagnati celoten program.

**Comment by vesnazupanc** [comment]
Aha, sem opazila, da sem zbrisala ukaz, kjer sem Vzroke spremenila v character pa mi mogoče zato ni prijela. Zdaj, ko jih najprej spremenim, mi dela.

Kaj pa če naprimer želim zamenjati `2010H1, 2010H2` ipd. v `2010`? 
Hotela sem tako:
`prebivalci$Polletje <- prebivalci$Polletje %>% strapplyc(???) %>% unlist() %>% as.numeric()`
in nevem kaj naj vpišem v strapplyc.

**Comment by jaanos** [comment]
V tem primeru funkciji `strapplyc` lahko podaš npr `"^([0-9]+)"` - torej pobereš vse številke na začetku niza. Podobno lahko še z `"([12])$"` pobereš še številko polletja (seveda ne smeš pred tem povoziti stolpca `Polletje`).

**Comment by vesnazupanc** [comment]
Aha, ok. Hvala za pomoč.
