### ISSUE TITLE
shiny

### ISSUE THREAD

**Issue by vesnazupanc** [vesnazupanc/APPR-2015-16#5]
Shiny mi ne dela. Aplikacijo mi zažene ampak se ne pokažeta tabela in graf. Javi mi tudi neko napako, ampak ne razumem kaj je narobe.

**Comment by jaanos** [comment]
Najprej svetujem, da ukaze `source` premakneš iz `server.R` v `shiny.r`, od tam pa `library(shiny)` v `lib/libraries.r`. Stavek `if` lahko potem pobrišeš iz `server.R`. Potem lahko za zagon Shiny aplikacije uporabiš `shiny.r`, aplikacijo pa bo mogoče vključiti tudi v poročilo brez ponovnega zaganjanja celotnega programa.

Napako ti javi, ker v `server.R` pričakuješ podatke v `input$var`, ustreznemu izbirniku pa je ime `"stopnja"`. Če samo to spremeniš, bo sicer delovalo pri izbiri določene stopnje, bo pa še vedno na začetku javljalo napako, saj očitno želi izrisovati zemljevid, preden se izbirnik sploh ustvari (to bi sicer lahko preprečila tako, da bi izbirnik naredila v `ui.R`). Da to preprečiš (in da bo tudi izbira _Vse_ delovala), si lahko vnaprej pripraviš podatke, nato pa jih po potrebi filtriraš:

``` R
  podatki <- Umrli_stopnje %>% filter(Leto == 2014)
  output$zemljevid<-renderPlot({
    if (length(input$stopnja) > 0 && input$stopnja %in% podatki$Stopnja) {
      data <- podatki %>% filter(Stopnja == input$stopnja)
    } else {
      data <- podatki
    }
    ggplot() + geom_polygon(data = data %>%
                              right_join(SLO, by = c("Regija" = "NAME_1")),
                            aes(x = long, y = lat, group = group,
                                fill = Stopnja), color = "grey") +
      scale_fill_manual(values = c("nizka" = "green",
                                   "normalna" = "orange",
                                   "visoka" = "red")) +
      geom_text(data = SLO %>% group_by(id, NAME_1) %>% summarise(x = mean(long), y = mean(lat)),
                aes(x = x, y = y, label = NAME_1), size = 2.5)
  })
```

Svetujem še, da iz `vizualizacija.r` premakneš ukaz `print` na koncu v poročilo - tako se ti pri zagonu Shinyja ne bo po nepotrebnem izrisal zemljevid.

**Comment by vesnazupanc** [comment]
Hvala, zdaj mi vse dela.
Se pravi, če nimam možnosti "VSE" pa lahko naredim tako kot sem imela narejeno?

Še eno vprašanje imam. Zdaj sem želela dodati še grafe, ki prikazujejo umrle glede na leto (po tem ko si že izbereje spol ipd.), pa mi javi napako.. 

GRAF:

`data <- umrli.vzrok %>% group_by(Spol,Leto,Vzrok) %>% 
      summarise(Umrli = sum(Število.umrlih)) %>% 
      filter(Spol == input$spol, Vzrok == input$vzrok)`

`ggplot() + geom_bar(data = data, aes(x=Leto, y=Umrli)) +
      labs(title ="Število umrlih glede na vzrok")+
      theme_bw()`

Napaka je: `Error:_ stat_count() must not be used with a y aesthetic.`

**Comment by jaanos** [comment]
Tako, brez možnosti _Vse_ je bilo v redu, kot je bilo. Vseeno bi ti pa svetoval, da statične elemente narediš kar v `ui.R`, saj bo tako aplikacija delovala hitreje in z manj napakami. Povsod, kjer imaš v `server.R` funkcijo `renderUI`, torej premakni njeno vsebino v `ui.R` namesto ustrezne funkcije `uiOutput`. Uporaba `renderUI` in `uiOutput` je sicer smiselna takrat, ko se lahko sam element spreminja.

Da ti bo prikazalo graf, h `geom_bar` dodaj še parameter `stat = "identity"`. Pazi tudi na to, da daš različnim elementom različna imena - trenutno imaš dva izbirnika z imenom `"spol"`, zaradi česar ti dejansko deluje samo eden. Seveda pazi, da po preimenovanju spremeniš tudi ustrezna imena v `server.R`.

**Comment by vesnazupanc** [comment]
Aha, sem premaknila in popravila pa mi vse dela. Hvala!
