### ISSUE TITLE
Še zadnji popravek in oddaja projekta

### ISSUE THREAD

**Issue by vesnazupanc** [vesnazupanc/APPR-2015-16#6]
Zanima me kako sploh lahko vlkjučim shiny v poročilo? 

Še to naredim, potem pa mislim da sem pripravljena na oddajo projekta, če se vam zdi v redu?

**Comment by jaanos** [comment]
Shiny v poročilo vključiš tako, da na želeno mesto dodaš blok kode z vrstico

``` R
shinyAppDir("shiny", options = list(width = "100%", height = 900))
```

in poročilo prevedeš v HTML. Ko te vpraša, ali želiš pognati Shiny, odgovori _Yes, Always_. Seveda lahko podano višino po potrebi spremeniš.

Drugače pa izgleda v redu, tako da lahko dodam povezavo na končno različico, ko meniš, da si končala. Medtem se lahko s profesorjem domeniš za termin zagovora.

**Comment by vesnazupanc** [comment]
Ali sedaj, ko sem prevedla poročilo v HTML in dala odgovor Yes, Always, sploh še lahko prevedem poročilo v PDF? Namreč mi poročila v pdf ne prevede, saj mi napiše:

> Runtime 'shiny' is not supported for latex output.
> Please change the output type of this document to HTML.
> In addition: There were 20 warnings (use warnings() to see them)
> Execution halted

Sicer sem del s shinyjem odstranila..

**Comment by jaanos** [comment]
Shiny je namenjen spletnim aplikacijam, tako da znotraj PDF ne bo deloval. Lahko pa seveda pustiš poročilo v obliki PDF, pa Shiny poganjaš posebej.

**Comment by vesnazupanc** [comment]
Ja, to razumem, ampak tudi če odstranim blok z shiny-jem mi ne prevede poročila v PDF..

**Comment by jaanos** [comment]
Odstrani še vrstico `runtime: shiny` iz glave dokumenta, pa ti bo prevedlo tudi v PDF.

**Comment by vesnazupanc** [comment]
Hvala!
